on: [push, pull_request]

name: Actions CI

jobs:
  build_and_test:
    name: integer-encoding-rs
    strategy:
      fail-fast: false
      matrix:
        features: ["tokio_async", "futures_async", ""]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --no-default-features --features=${{ matrix.features }}
      - run: cargo test --no-default-features --features=${{ matrix.features }}
      - run: cargo fmt -- --check
